version: '2.1'

services:
#  nginx:
#    build: ./nginx
#    links:
#      - nodejs:nodejs
#    ports:
#      - "80:80"

  web:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
    - 80:3000
    